name: test

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: ['16', '18']

    steps:
    - name: checkout
      uses: actions/checkout@v2
    - name: setup Node v${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: install utilities
      run: sudo apt install miller moreutils
    - run: npm install

    - run: npm run lint
    - run: npm run build
    - run: npm test
